apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-node
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: {{ .Release.Name }}-server
          image: 'brightmove/{{ .Chart.Name }}:{{ .Chart.AppVersion }}'
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "{{ .Values.otelExporterOtlpProtocol }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.otelExporterOtlpEndpoint }}"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "{{ .Values.otelExporterOtlpHeaders }}"
            - name: JAVA_OPTS
              value: >-
                -javaagent:/usr/local/tomcat/lib/opentelemetry-javaagent.jar
                -Dotel.logs.exporter=otlp
                -Dotel.semconv-stability.opt-in=http
                -Dotel.instrumentation.micrometer.base-time-unit=s
                -Dotel.service.name=jasperserver-{{ .Values.env }}
                -Dotel.resource.attributes=deployment.environment={{ .Values.env }},service.namespace=jasperserver,service.instance.id=$HOSTNAME
                -Denv={{ .Values.env }}
                -Xms{{ .Values.jvmHeapInit | default "1g" }}
                -Xmx{{ .Values.jvmHeapMax | default "1g" }}
                -Xrs
                -Xss256k
                -XX:+UseG1GC
                -XX:NewRatio=3
                -Dats_url={{ .Values.atsDatasource.url }}
                -Dats_user={{ .Values.atsDatasource.username }}
                -Dats_password={{ .Values.atsDatasource.password }}
                -Dmysql_connection="{{ .Values.jasperDatasource.url }}"
                -Dks=/usr/local/tomcat/
                -Dksp=/usr/local/tomcat/
          ports:
            - containerPort: 8080
              name: tc-port
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: general