apiVersion: v2
name: bright-reports-qa
version: 1.0.4
appVersion: qa
description: Bright Reports Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - reports
  - brightreports
sources:
  - https://github.com/BrightMove/bright-reports.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
  - name: Jake Pharr
    email: jake.pharr@brightmove.com
deprecated: false
annotations:
  created: "04/06/2023"
