apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-confluence-data
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09df0e6f64b71a013

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-efs-claim
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-confluence-data
  resources:
    requests:
      storage: 10Gi