apiVersion: v2
name: brightmove-ats-qa
version: 1.0.20
appVersion: qa
description: BrightMove ATS Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - ats
sources:
  - https://github.com/BrightMove/brightmove-ats.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
  - name: Jake Pharr
    email: jake.pharr@brightmove.com
deprecated: false
annotations:
  created: "03/24/2023"
