namespace: brightmove
dockerImageName: brightmove-ats
springProfiles: qa
env: qa
jvmHeapInit: 1536m
jvmHeapMax: 1536m
memcached:
  cluster:
    discovery:
      endpoint: tomcat-sessions-lle2.fsaqmz.cfg.use1.cache.amazonaws.com:11211
  sessionManager:
    className: de.javakaffee.web.msm.MemcachedBackupSessionManager
msm:
  kryo:
    bufferSize:
      max: 5242880