apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-node
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: tcp-80
      port: 80
      targetPort: 80
    - protocol: TCP
      name: tcp-53000
      port: 53000
      targetPort: 53000
  selector:
    app: {{ .Release.Name }}-node
