apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: {{ .Release.Name }}-server
          image: brightmove/solr-indexer:1.7.15
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
          env:
            - name: APP_ENV
              value: "production"
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active={{ .Values.springProfiles }} -Denv={{ .Values.env }} -Xms{{ .Values.jvmHeapInit | default "256m" }} -Xmx{{ .Values.jvmHeapMax | default "256m" }} -Xrs -XX:+UseG1GC -XX:NewRatio=3"
          ports:
            - containerPort: 8080
              name: tc-port
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: general