apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-aws-secretsmanager
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsSecretsManager.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
