apiVersion: v2
name: brightmove-ats-dev
version: 1.0.1
appVersion: latest
description: BrightMove ATS Application.
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/brightmove-icon.png
keywords:
  - brightmove
  - ats
sources:
  - https://github.com/BrightMove/brightmove-ats.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
deprecated: false
annotations:
  created: "03/20/2023"
