apiVersion: v2
name: bright-sync-qa
version: 1.0.6
appVersion: qa
description: BrightSync Email Manager
type: application
icon: https://bm-helm.s3.amazonaws.com/icons/bright-sync-logo.svg
keywords:
  - brightmove
  - exchange
  - email
sources:
  - https://github.com/BrightMove/bright-sync.git
maintainers:
  - name: David Webb
    email: dwebb@brightmove.com
deprecated: false
annotations:
  created: "12/15/2022"
