namespace: default
dockerImageName: bright-sync
springProfiles: default
env: default
jvmHeapInit: 1g
jvmHeapMax: 1g
jmxPort: 9999
javaagent:
quartzDatasource:
  url: jdbc:oracle:thin:@qa.oracle.brightmove.com:1521:BMQ1
  username:
  password:
atsDatasource:
  url: jdbc:oracle:thin:@qa.oracle.brightmove.com:1521:BMQ1
  username:
  password:

