namespace: default
dockerImageName: bright-sync
springProfiles: default
env: default
otelExporterOtlpProtocol: "http/protobuf"
otelExporterOtlpEndpoint: "https://otlp-gateway-prod-us-central-0.grafana.net/otlp"
otelExporterOtlpHeaders: "Authorization=Basic NDgwNzMxOmV5SnJJam9pT0RnMk9HTXlaVEl3T1daak9EUTJOekJtWmpRMk5tTTFPR0V3WXpkak5UaGlPREU0TWpsa1lpSXNJbTRpT2lKUGNHVnVWR1ZzWlcxbGRISjVJaXdpYVdRaU9qYzBPRGMwTVgwPQ=="
jvmHeapInit: 1g
jvmHeapMax: 1g
jmxPort: 9999
javaagent:
quartzDatasource:
  url: jdbc:oracle:thin:@qa.oracle.brightmove.com:1521:BMQ1
  username:
  password:
atsDatasource:
  url: jdbc:oracle:thin:@qa.oracle.brightmove.com:1521:BMQ1
  username:
  password:

