apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-node
    tags.datadoghq.com/env: {{ .Values.env }}
    tags.datadoghq.com/service: {{ .Release.Name }}
    tags.datadoghq.com/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node
        tags.datadoghq.com/env: {{ .Values.env }}
        tags.datadoghq.com/service: {{ .Release.Name }}
        tags.datadoghq.com/version: {{ .Chart.AppVersion }}
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.46.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: {{ .Release.Name }}-server
          image: 'brightmove/{{ .Values.dockerImageName }}:{{ .Chart.AppVersion }}'
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 10
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "{{ .Values.otelExporterOtlpProtocol }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.otelExporterOtlpEndpoint }}"
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: "{{ .Values.otelExporterOtlpHeaders }}"
            - name: JAVA_OPTS
              value: >-
                -javaagent:opentelemetry-javaagent.jar
                --add-opens=java.base/java.nio=ALL-UNNAMED
                -Dotel.logs.exporter=otlp
                -Dotel.semconv-stability.opt-in=http
                -Dotel.instrumentation.micrometer.base-time-unit=s
                -Dotel.service.name=jobgorilla-{{ .Values.env }}
                -Dotel.resource.attributes=deployment.environment={{ .Values.env }},service.namespace=brightmove,service.instance.id=${HOSTNAME}
                -Dspring.profiles.active={{ .Values.springProfiles }}
                -Denv={{ .Values.env }}
                -Xms{{ .Values.jvmHeapInit | default "256m" }}
                -Xmx{{ .Values.jvmHeapMax | default "256m" }}
                -Xrs
                -XX:+UseG1GC
                -XX:NewRatio=3
            - name: DD_LOGS_INJECTION
              value: "true"
          ports:
            - containerPort: 8080
              name: tc-port
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: general