apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-nexus-data
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0959edd5abadf250e

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-efs-claim
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-nexus-data
  resources:
    requests:
      storage: 30Gi
