apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-node
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: {{ .Chart.Name }}-server
          image: brightmove/{{ .Chart.Name }}:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 8080
              name: {{ .Chart.Name }}-port
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: general