apiVersion: apps/v1
kind: Deployment
metadata:
  name: flat-pdf-deployment
  namespace: tools
  labels:
    app: flat-pdf-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flat-pdf-node
  template:
    metadata:
      labels:
        app: flat-pdf-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: flat-pdf-server
          image: brightmove/flat-pdf:1.1.0
          ports:
            - containerPort: 8080
              name: flat-pdf-port
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: general