apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-node
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: http-temp
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}-node
