apiVersion: v1
kind: Service
metadata:
  name: flat-pdf-service
  namespace: tools
  labels:
    app: flat-pdf-node
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: http-temp
      port: 80
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8080
  selector:
    app: flat-pdf-node
