namespace: brightmove
dockerImageName: brightmove-ax-legacy
springProfiles: qa
env: qa
otelExporterOtlpProtocol: "http/protobuf"
otelExporterOtlpEndpoint: "https://otlp-gateway-prod-us-central-0.grafana.net/otlp"
otelExporterOtlpHeaders: "Authorization=Basic NDgwNzMxOmV5SnJJam9pT0RnMk9HTXlaVEl3T1daak9EUTJOekJtWmpRMk5tTTFPR0V3WXpkak5UaGlPREU0TWpsa1lpSXNJbTRpT2lKUGNHVnVWR1ZzWlcxbGRISjVJaXdpYVdRaU9qYzBPRGMwTVgwPQ=="
jvmHeapInit: 1g
jvmHeapMax: 1g
atsMaxActive: 150
atsPassword: ats4qa1pass
atsUrl: jdbc:oracle:thin:@qa.oracle.brightmove.com:1521:BMQ1
atsUser: ats_q
quartzPassword: ats_quartz4qa1pass
quartzUrl: jdbc:oracle:thin:@qa.oracle.brightmove.com:1521:BMQ1
quartzUser: ats_quartz_q
memcached:
  cluster:
    discovery:
      endpoint: tomcat-sessions-lle2.fsaqmz.cfg.use1.cache.amazonaws.com:11211
  sessionManager:
    className: de.javakaffee.web.msm.MemcachedBackupSessionManager
msm:
  kryo:
    bufferSize:
      max: 5242880