apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-node
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: tcp-8161
      port: 8161
      targetPort: 8161
    - protocol: TCP
      name: tcp-61616
      port: 61616
      targetPort: 61616
  selector:
    app: {{ .Release.Name }}-node
